### ISSUE TITLE
Translate blog post "CNIL" from French to English

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/website#102]
Translate the following article from French to English:

https://exodus-privacy.eu.org/en/post/retour-sur-notre-rencontre-avec-la-cnil/

**Comment by MKlblangenois** [comment]
Related to #103

**Comment by bidetaggle** [comment]
Hi! As a French native speaker, I'd like to work on this issue.

**Comment by Gu1nness** [comment]
You're more than welcomed to work on this \o/

**Comment by MKlblangenois** [comment]
Translated in #104 😊

**Comment by bidetaggle** [comment]
Bro, didn't you see that it was assigned to me in the earlier messages?
There are plenty of other open issues for translation English -> French, what's your motivation in that move?

😊
