### ISSUE TITLE
Translate blog post "Médiation numérique, vie privée et smartphones, retours sur un questionnaire" from French to English

### ISSUE THREAD

**Issue by Gu1nness** [Exodus-Privacy/website#109]
Translate the following article from French to English:

https://exodus-privacy.eu.org/fr/post/mednum/

**Comment by bidetaggle** [comment]
As mentioned in https://github.com/Exodus-Privacy/website/pull/105#discussion_r499473382

TODO: Replace the link to the new translated file in [content/post/AG2020.en.md](https://github.com/Exodus-Privacy/website/blob/hugo/content/post/AG2020.en.md) on line 19:
```diff
- [...] https://exodus-privacy.eu.org/fr/post/mednum/). [...]
+ [...] https://exodus-privacy.eu.org/en/post/mednum/). [...]
```
