### ISSUE TITLE
Redesign of the website

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/website#111]
![image](https://user-images.githubusercontent.com/6069449/96033685-b3bba300-0e60-11eb-868c-23eb52503f9e.png)

**Comment by Gu1nness** [comment]
Courage à vous 3 !

**Comment by jfoucry** [comment]
I would like to propose, if we need some, to use {ForkAwesome](https://forkaweso.me/Fork-Awesome/) project icons instead of FontAwesome. I already generate the fonts for myself (from the `SVG`file with a provided `makefle`) and the `css` are provided too.
