### ISSUE TITLE
Videos torrent download doesn't start

### ISSUE THREAD

**Issue by adrienandrem** [Exodus-Privacy/website#138]
[PeerTube videos](https://video.exodus-privacy.eu.org/video-channels/2ab4458d-0b3c-485a-aeaf-792cd0842bc8/videos) download via torrent doesn't start.
Looks like PeerTupe isn't seeding :thinking:

**Comment by pnu-s** [comment]
@jfoucry Any news on this?

**Comment by Jean-BaptisteC** [comment]
The problem can be closed, because instance Peertube is shut down
