### ISSUE TITLE
The Exodus Privacy app is no longer available on the Google Play Store

### ISSUE THREAD

**Issue by roastchicken** [Exodus-Privacy/website#142]
On the ["what" page](https://exodus-privacy.eu.org/en/page/what/#%CE%B5xodus-android-application) (in English at least) it states "The application is available on F-Droid and Google Play." As of today, [this is not true](https://play.google.com/store/apps/details?id=org.eu.exodus_privacy.exodusprivacy). I assume it was removed by Google; I'm sure others know more about this than I.

If this is the only page that mentions Google Play, I'm happy to submit a pull request. Although I think someone more familiar with the project should write the copy, ideally.

**Comment by pnu-s** [comment]
Hello @roastchicken 

Thanks for raising this issue.
Some details about why it got removed is available here: https://github.com/Exodus-Privacy/exodus-android-app/issues/111

I guess we could at least add a note on our website and link this issue.

Feel free to submit a PR, that would be greatly appreciated :)
