### ISSUE TITLE
Arriver sur le site français depuis une application en français

### ISSUE THREAD

**Issue by maiwann** [Exodus-Privacy/website#165]
Test réalisé sur la nouvelle application : 
## Page À propos

Lorsque je clique sur " **Site web** En savoir plus sur Exodus Privacy" j'arrive sur la page d'accueil  `exodus-privacy.eu.org` en anglais.
Pour les personnes peu à l'aise en anglais (qui correspondent à une grande partie du public rencontré en atelier / médiation numérique) cela peut être rébarbatif, entraînant un retour en arrière sur l'app qui elle, est en français.
Or, puisque le site existe en français, cela serait chouette qu'il soit possible d'arriver sur la version française du site, supprimant cette friction et permettant de découvrir l'association ! 🌟

**Comment by dimitri-bourreau** [comment]
Autre point de vue : visiter `https://exodus-privacy.eu.org/` redirige automatiquement vers `https://exodus-privacy.eu.org/en/`.

Cette redirection est maintenue même si précédemment nous avons sélectionné la langue française.

https://user-images.githubusercontent.com/32717624/199340639-8243ccb9-4c98-4a6a-ae1b-3d772d590426.mov

Il semble que ce comportement soit l'attendu.

Nous avons deux solutions : 

- Modifier le site afin que visiter `https://exodus-privacy.eu.org/` affiche par défaut la langue française.
- Modifier l'application pour rediriger vers `https://exodus-privacy.eu.org/fr/` ou `https://exodus-privacy.eu.org/en/` dynamiquement.

Pour cette seconde solution, je ne maîtrise pas le langage mais il me semble qu'un bon point de départ serait [ici](https://github.com/Exodus-Privacy/exodus-android-app/blob/2339fc659ef59f48a80debf5a7789a8e42cf82ed/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt#L31).

Si la seconde solution est la préférée, il faudrait [créer une issue sur le dépôt de l'application mobile](https://github.com/Exodus-Privacy/exodus-android-app/issues/new). ✌️

**Comment by codeurimpulsif** [comment]
Pour l'application mobile je pense qu'il faudrait faire une issue sur le dépôt de l'application mobile en effet, par contre il me semble en effet normal que par défaut (nous ne détectons pas la langue du navigateur) ça soit la version anglaise qui s'affiche.

Je pense qu'il faut faire cette modification sur l'application mobile.
