### ISSUE TITLE
Replace PrivacyTools with PrivacyGuides

### ISSUE THREAD

**Issue by kremzli** [Exodus-Privacy/website#178]
Replace the link to PrivacyTools to [PrivacyGuides](https://www.privacyguides.org/)
The link is on [this page](https://reports.exodus-privacy.eu.org/en/info/next/). I couldnt find that page to make a PR

PrivacyTools is full of non-private services and software (filled with affiliate links), and the creation of PrivacyGuides was a pretty big deal. I also think they are a way better upgrade, taking in mind security and having much better standards, and having actual guides on how to threat model and other things.
See more here: 
https://www.privacyguides.org/about/privacytools/#privacytoolsio-now

**Comment by kremzli** [comment]
Additional evidence of PrivacyTools' badness in this forum post:
https://discuss.techlore.tech/t/has-anyone-seen-this-video-wondering-your-thoughts/792/20

**Comment by Jean-BaptisteC** [comment]
Please check this https://github.com/Exodus-Privacy/exodus/issues/464

**Comment by privacytoolsIO** [comment]
https://www.privacytools.io/guides/jonah-aragon-privacyguides-failed-attempt-to-takeover

**Comment by pnu-s** [comment]
Closing as duplicate from the issue in exodus repository
