### ISSUE TITLE
Update Hugo to v0.59.1

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/website#199]
I know update Hugo breaks website,  but I have doing somes tests and we can update Hugo to v0.59.1 without doing too much work.
To upgrade to this version, we need:
- Fix `$index` in `themes/hugo-bootstrap/layouts/section/code.html`
- Migrate all media to `static` directory

I have tried  to upgrade to v0.60 -> HTML sections of website is not visible (I guess it's caused by module used to generate markdown https://github.com/gohugoio/hugo/releases/tag/v0.60.0)

**Comment by codeurimpulsif** [comment]
I think we will stick to this version until we migrate to another software like Pelican

**Comment by pnu-s** [comment]
Agreed, I don't think it makes sense to upgrade some versions if we cannot upgrade to the latest one.
Let's wait for a total rewrite, for now keeping the existing hugo version is not a problem.
