### ISSUE TITLE
Error in statut of association

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/website#210]
![image](https://github.com/Exodus-Privacy/website/assets/87148630/706f081e-8110-408c-90f8-da0a14e6e5ea)

**Comment by pnu-s** [comment]
@Jean-BaptisteC What's the error here? :)

**Comment by pnu-s** [comment]
The `[Redacted]` is put on purpose in order to avoid revealing private information, such as address in this case.

So nothing to worry about :)
