### ISSUE TITLE
Put the english press first in the en.md page ?

### ISSUE THREAD

**Issue by MeTaLPoU** [Exodus-Privacy/website#35]
I think it should be more relevant to put the english press for the english audience.

**Comment by sztxr** [comment]
I'd like to help out with this as well :)

**Comment by MeTaLPoU** [comment]
Oh, thank you :)
You will find a file called "press.en.md". You will have to switch the French and the English press in this file :)
If you need any help, please ask.

**Comment by simpnu** [comment]
Done by @sztxr on #45 \o/
