### ISSUE TITLE
Separate press links by year

### ISSUE THREAD

**Issue by simpnu** [Exodus-Privacy/website#36]
I think the press page would be more readable if we separate the pages by year, such as:

> - FR
>   - 2019
>   - 2018
>   - 2017
> - EN
>   - 2019
>   - 2018
>   - 2017

**Comment by sztxr** [comment]
I'd like to help you with this :)

**Comment by sztxr** [comment]
Where you thinking of something like this?

## French press
### 2019
  - **Capital.fr** - *Aug 30 2019* - Données perso : 10 réflexes à adopter pour protéger votre vie privée
  - etc
### 2018
  - **Next Inpact** - *Nov 24 2018* - L’effet du RGPD sur les trackers des applications Android, selon Exodus Privacy
  - etc

**Comment by simpnu** [comment]
Hello @sztxr and thanks!
That's pretty much what I had in mind yes :)

**Comment by sztxr** [comment]
This is to be done on both `press.fr.md and` `press.end.md` correct?

**Comment by simpnu** [comment]
Yes :)

**Comment by simpnu** [comment]
Done by @sztxr on #46 \o/
