### ISSUE TITLE
Changing language redirect to home page

### ISSUE THREAD

**Issue by jfoucry** [Exodus-Privacy/website#40]
When we change language (from french to english or nglish to french) the navigation goes back to homepage instead of beeing in the same page ut in the new language.

Example :
Today:
`accounting (english) → Switching language to french → homepage`

Should be:
`accoounting (english) → Switching language to french → accounting (french)`

**Comment by Gu1nness** [comment]
Yup.
Bug confirmed, I'm working on it.
