### ISSUE TITLE
Add fb logo to the website

### ISSUE THREAD

**Issue by Gu1nness** [Exodus-Privacy/website#50]
The page https://exodus-privacy.eu.org/en/page/contribute/ contains all the logos but the FB one.
Moreover, they are not vertically aligned.

**Comment by simpnu** [comment]
Hmm, all the logos seem to be here for me (and are vertically aligned).
Same for the page in French.

![image](https://user-images.githubusercontent.com/6069449/66223323-7a8c1700-e6d3-11e9-95e9-b2bde1fb3de7.png)

**Comment by Gu1nness** [comment]
Okay, my bad.
Looks like the problem is on the client side (FF-nightly is broken with fontawesome maybe ?)
