### ISSUE TITLE
Links to tags are not internationalized

### ISSUE THREAD

**Issue by simpnu** [Exodus-Privacy/website#56]
If you follow the link of a tag from a blog post (such as https://exodus-privacy.eu.org/en/post/tracking-trackers/) you will end on a 404 error page because the link is not internationalized -> https://exodus-privacy.eu.org/tags/trackers/

I don't really know where to look at, I'm guessing it could be in the theme itself.

Note: this currently blocks #18

**Comment by jfoucry** [comment]
Hum… I looked at `recent_articles.html` and `tag_cloud.html` which seems part of the new page and the url are not similar. 
I mean in `recent_articles.html` the final url is construct as this:
```
<p class="item-title"><a href="{{ .RelPermalink }}" class="title">{{ .Title | markdownify}}</a></p>
```

In `tag_cloud.html` it's:
```
<a href="{{ (print "tags/" ($name | urlize | lower) "/") | relURL }}" class="badge badge-primary">
```
Is the difference between `.RelPermalink` and `relURL` could be the issue ?

This is just a first look, I did not try to make a change in `tag_cloud.html` for now.
