### ISSUE TITLE
No redirection to translated pages

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/website#6]
> **Note: issue migrated from internal git**

The website does not handle well the internationalization.

For example, https://exodus-privacy.eu.org/page/who/ should automatically redirect to https://exodus-privacy.eu.org/fr/page/who/ or https://exodus-privacy.eu.org/en/page/who/ depending on the language of your browser, exactly how it is working for the main page http://exodus-privacy.eu.org/.
Instead, it serves an old cached version of the page.

**Comment by simpnu** [comment]
2 issues here:
- https://exodus-privacy.eu.org always redirects to english
- old pages such as https://exodus-privacy.eu.org/page/who/ are still present

@Gu1nness When do you think we can apply your patch for 1?
@codeurimpulsif for 2, should we simply add a beautiful 404 page and remove the old pages?

**Comment by simpnu** [comment]
@Gu1nness @codeurimpulsif any news on this? :)

**Comment by VedantPol** [comment]
hey , @pnu-s i would like to work on this issue :)

**Comment by pnu-s** [comment]
@VedantPol To be fair I'm not sure this is something which can be fixed on this repository, but if you find a way, feel free to open a PR that would be great!

**Comment by codeurimpulsif** [comment]
We still want language detection for the home page? (I think english is ok, and we have a language selector)

If we still want the language detection on home page I think we need to use a cookie.

**Comment by pnu-s** [comment]
I think we want to have the same behavior for https://exodus-privacy.eu.org/page/what/ as for https://exodus-privacy.eu.org (which means no 404).

It does not really matter to me which language it redirects to.

**Comment by codeurimpulsif** [comment]
How do you find this URL (https://exodus-privacy.eu.org/page/what/)? I can't find it anywhere on our website.

**Comment by pnu-s** [comment]
It does not, but it means that if we want to add a link to any page (here our `What` page), it needs to be localized.

If that's ok, then let's close this issue.

**Comment by codeurimpulsif** [comment]
I think we don't have this need for our website at this time, yes I think we can close this issue
