### ISSUE TITLE
Add a reference to the "better understand" page in the What page

### ISSUE THREAD

**Issue by MeTaLPoU** [Exodus-Privacy/website#67]
In the What page, we talk about our tools and our Popularization supports. We could mention our new "better understand" page, but i don't know where.

**Comment by AkshadK7** [comment]
Should I create a sample base "Better Understand" Page and link it through the Navbar ?

You could assign the task to me if you like for a HacktoberFest PR !

P.S:  You can always check out my Web Dev skills through my profile :)

**Comment by pnu-s** [comment]
@AkshadK7 The plan is about adding a link and a couple of words about our "better understand" page (https://reports.exodus-privacy.eu.org/en/info/understand/) in our "What" page (https://exodus-privacy.eu.org/en/page/what/), presumably in the "Outreach: Learn More" section
