### ISSUE TITLE
Add Github link to website

### ISSUE THREAD

**Issue by simpnu** [Exodus-Privacy/website#7]
We should add the link to this repository somewhere on the website (in the footer for instance).

**Comment by sztxr** [comment]
I can do this. Do you want the Github icon?

**Comment by simpnu** [comment]
It would be easier to use the Github icon as it doesn't need to be translated but:
- I'm not sure how it would fit in the footer
- I don't know if this is totally clear for an uninitiated person

If you find a way to add the [Github logo](https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/1200px-Octicons-mark-github.svg.png) in a nice way, why not :). Otherwise, I'd stick with just a link (with a label such as "Source code"?)

**Comment by sztxr** [comment]
I'll try out the icon + link, if that fails I'll stick to just the link :)

**Comment by simpnu** [comment]
Done in #52 :)
