### ISSUE TITLE
Move to Weblate

### ISSUE THREAD

**Issue by comradekingu** [Exodus-Privacy/website#80]
Crowdin is one big privacy mess https://support.crowdin.com/cookies/

First #2 should be fixed and fill one can fill out https://weblate.org/hosting/ :)

**Comment by pnu-s** [comment]
We currently don't have any plans about moving from our current translation platform, despite its drawbacks

Closing this issue!

**Comment by comradekingu** [comment]
@pnu-s It is possible to just put up a project on Hosted now https://hosted.weblate.org/create/project/?billing=520 :)
