### ISSUE TITLE
Translate blog post "εxodus static analysis" from English to French

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/website#98]
Translate the following article from English to French:

https://exodus-privacy.eu.org/en/post/exodus_static_analysis/

**Comment by MKlblangenois** [comment]
@pnu-s should you want to translate the title of this blog too or you want to keep it in english ?

**Comment by jfoucry** [comment]
Hello,

The french title could be « εxodus, analyse statique » 

What your opinion @pnu-s ?

**Comment by Gu1nness** [comment]
I would rather go for «L'analyse statique d'εxodus»

**Comment by pnu-s** [comment]
I agree with @Gu1nness's proposal :)

**Comment by MKlblangenois** [comment]
Translated in #110 🙂
